trigger:
  branches:
    include:
    - 'main'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - '*'
    exclude:
    - '**/*.md'
    - docs

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: tagName
  value: "$(Build.BuildNumber)"
- name: serviceName
  value: "schedule-services"
- name: latestImageName
  value: "openreservation/$(serviceName):latest"
- name: imageName
  value: "openreservation/$(serviceName):$(tagName)"
- group: "docker"

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk'
  inputs:
    packageType: sdk
    version: 8.0.x
    includePreviewVersions: true

- script: dotnet --info
  displayName: 'dotnet info'

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: dotnet test 
  displayName: 'dotnet test'

- script: docker build -f ./OpenReservation.ScheduleServices/Dockerfile -t $(imageName) -t $(latestImageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
    docker push $(latestImageName)
  displayName: 'Push docker image'

- task: Kubernetes@1
  displayName: 'kubectl update deployment'
  inputs:
    kubernetesServiceEndpoint: 'aks-hk-01'
    command: 'apply'
    arguments: '-f https://raw.githubusercontent.com/OpenReservation/OpenReservation.ScheduleServices/main/k8s/manifests/deployment.yaml'

- task: Kubernetes@1
  displayName: 'kubectl set image'
  inputs:
    kubernetesServiceEndpoint: 'aks-hk-01'
    command: 'set'
    arguments: 'image deployment/$(serviceName) $(serviceName)=$(imageName)'

- script: |
    dotnet tool update -g dotnet-execute
    export PATH="$PATH:$HOME/.dotnet/tools"
    dotnet-exec "https://github.com/OpenReservation/scripts/blob/main/deploy/azure-pipelines-notification.cs"
  displayName: 'Push notification'  
  env:
    # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
    # can not directly reference a secret value
    DingBotWebhookUrl: $(DingBotWebhookUrl)