trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - '*'
    exclude:
    - '**/*.md'
    - /docs/
    - /k8s/

pool:
  vmImage: 'ubuntu-latest'

variables:
  tagName: '$(Build.BuildNumber)'
  serviceName: 'schedule-services'
  latestImageName: 'openreservation/$(serviceName):latest'
  imageName: 'openreservation/$(serviceName):$(tagName)'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET sdk'
  inputs:
    packageType: sdk
    version: 8.0.x
    includePreviewVersions: true

- script: dotnet --info
  displayName: 'dotnet info'

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: dotnet test 
  displayName: 'dotnet test'

- script: docker build -f ./OpenReservation.ScheduleServices/Dockerfile -t $(imageName) -t $(latestImageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
    docker push $(latestImageName)
  displayName: 'Push docker image'
- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    sshEndpoint: 'weihanli-vm'
    runOptions: inline

    inline: |
      kubectl set image deployment/$(serviceName) $(serviceName)=$(imageName)
