apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-services
  namespace: default
  labels:
    app: schedule-services
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: schedule-services
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: schedule-services
    spec:
      containers:        
        - name: schedule-services
          image: openreservation/schedule-services:latest
          imagePullPolicy: Always
          env:
          - name: AppSettings__NotificationAuthApiKey
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: NotificationAuthApiKey
          - name: AppSettings__JdGzfConfig__UserName
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: JdGzf__UserName
          - name: AppSettings__JdGzfConfig__Password
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: JdGzf__Password
          - name: QWeatherApiQueryUrl
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: QWeatherApiQueryUrl
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 8080
