apiVersion: v1
kind: Service
metadata:
  name: schedule-services
  namespace: default
  annotations:
    prometheus.io/should_be_scraped: "true"
  labels:
    app: schedule-services
spec:
  selector:
    app: schedule-services
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
